### ISSUE TITLE
Setting up a kanban board for the Recipe App

### ISSUE THREAD

**Issue by TadesseDev** [Tadesse-Alemayehu/Recipe-app#15]
# In this project. 
---
- We are two. @Tadesse-Alemayehu and @marilirulita 
- we have set up our kanban board based on project requirements.
- [link to the project](https://github.com/users/Tadesse-Alemayehu/projects/5/views/1)

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media1.giphy.com/media/sR9nilEznDoSlga667/giphy.gif"/>

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by TadesseDev** [comment]
Thank you, @mukhammadrizooff
